# Generated by Django 3.1.2 on 2020-11-02 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='video_image')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='User name')),
                ('body', models.CharField(choices=[('rp', 'ruptured plaque'), ('er', 'erosion'), ('cn', 'calcified nodule'), ('none', 'no vulanable plaque'), ('in', 'indistinguishable')], max_length=20, verbose_name='Classification')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
    ]
