# Generated by Django 3.1.2 on 2020-11-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20201102_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=20, verbose_name='User name'),
        ),
    ]
